---
title: "Kardex"
author: "Carmen"
date: "29 de agosto de 2016"
output: html_document
 ---
##Lista de Calificaciones
### Otoño 2013
+ Programación Actuarial I  5
+ Introducción a la Profesión Actuarial 7
+ DHPC 8
+ Conceptos de Cálculo 5
+ Matemáticas básicas  7
+ Problemas de mat. básicas 7

###Primavera 2014
+ Teoría del interés I 5
+ Microeconomía 9
+ Conceptos de cálculo 10
+ Geometría Analítica  10
+ Programación Actuarial I 7

###Otoño 2014
+ Programación Actuarial II 7
+ Teoría del interés I 9
+ Macroeconomía 8
+ Formación Humana y Social 8
+ Teoría de Ecuaciones 7

###Primavera 2015
+ Programación Actuarial III 5
+ Teoría del Interés II 8
+ DHTIC 8
+ Cálculo diferencial 8
+ Intr. a las Estr. Algebraicas 5
+ Álgebra Lineal I 9

###Otoño 2015
+ Contabilidad General 9
+ Sistema Financiero Mexicano 10
+ Demografía I 9
+ Cálculo integral 9
+ Intr. a las Estr. Algebraicas 9

###Primavera 2016
+ Matemáticas Actuariales I 7
+ Derivados Financieros     9
+ Reg. Acad. y Cient. del Esp. 8
+ Cal. Difer. en Var. Variables 5
+ Ecuaciones Diferenciales I   10
+ Probabilidad I 6

### Otoño 2016
+ Programación Actuarial III
+ Cal. Difer. en Var. Variables
+ Matemáticas Actuariales II
+ Econometría I
+ Probabilidad II